local map = vim.keymap.set

map("n", "-", "<cmd>Oil --float<CR>", { desc = "Open parent directory" })
map("n", "gl", vim.diagnostic.open_float, { desc = "Open diagnostics" })
map("n", "<leader>k", function()
  require("blink.cmp").show_documentation()
end, { desc = "Show completion docs" })
map("n", "<leader>cf", function()
  require("conform").format({ lsp_format = "fallback" })
end, { desc = "Format current file" })
map("t", "<C-q>", [[<C-\><C-n>]])

map("n", "<leader>ff", function() require("fzf-lua").files() end, { desc = "Find files" })
map("n", "<leader>fg", function() require("fzf-lua").live_grep() end, { desc = "Live grep" })
map("n", "<leader>fc", function()
  require("fzf-lua").files({ cwd = vim.fn.stdpath("config") })
end, { desc = "Find in Neovim configuration" })
map("n", "<leader>fh", function() require("fzf-lua").helptags() end, { desc = "Find help" })
map("n", "<leader>fk", function() require("fzf-lua").keymaps() end, { desc = "Find keymaps" })
map("n", "<leader>fb", function() require("fzf-lua").buffers() end, { desc = "Find buffers" })
map("n", "<leader>fw", function() require("fzf-lua").grep_cword() end, { desc = "Find current word" })
map("n", "<leader>fW", function() require("fzf-lua").grep_cWORD() end, { desc = "Find current WORD" })
map("n", "<leader>fd", function() require("fzf-lua").diagnostics_document() end, { desc = "Find diagnostics" })
map("n", "<leader>fr", function() require("fzf-lua").resume() end, { desc = "Resume FZF" })
map("n", "<leader>fo", function() require("fzf-lua").oldfiles() end, { desc = "Find old files" })
map("n", "<leader>/", function() require("fzf-lua").lgrep_curbuf() end, { desc = "Grep current buffer" })
map("n", "<leader>sb", function() require("fzf-lua").git_branches() end, { desc = "Show branches" })
map("n", "<leader><leader>", function() require("fzf-lua").buffers() end, { desc = "Find existing buffers" })

map("n", "W" .. vim.keycode("<Up>"), "<C-w>5+", { desc = "Resize window up" })
map("n", "W" .. vim.keycode("<Down>"), "<C-w>5-", { desc = "Resize window down" })
map("n", "W" .. vim.keycode("<Left>"), "<C-w>5<", { desc = "Resize window left" })
map("n", "W" .. vim.keycode("<Right>"), "<C-w>5>", { desc = "Resize window right" })
map("n", "W=", "<C-w>=", { desc = "Equalize window sizes" })
map("n", "Wc", "<C-w>c", { desc = "Close current window" })
map("n", "Ws", ":vsplit<CR>", { desc = "Open vertical split" })
map({ "n", "i" }, "<F3>", ":vsplit | terminal<CR>", { desc = "Open terminal" })
